Show icons for items
BluSunrize/EngineersManual pull request #2
Opened 2022-06-06 14:58 UTC by malte0811

Using the data uploaded by BluSunrize/ImmersiveEngineering#5311.

I've also switched the available branches from a hardcoded list (which didn't contain 1.18.2 yet) to a list of "version branches" (starting `1.`) from GHs API. `latest` can be used for the latest branch (by version), `stable` for the default branch.

Reminder: I'm not a web dev, so expect some silly issues in this PR!

Currently running at https://malte0811.github.io/EngineersManual

2022-06-06 15:01 UTC, SkySom commented on src/resources.js
> +    "1.7.10", "1.8.9", "1.9.4", "1.10.2", "1.11.2", "1.13pre", "1.13"
Shouldn't master also be excluded?

2022-06-06 15:04 UTC, malte0811 commented on src/resources.js
> +    "1.7.10", "1.8.9", "1.9.4", "1.10.2", "1.11.2", "1.13pre", "1.13"
`master` doesn't start with `1.`, so it isn't considered anyway.

2022-06-06 16:38 UTC, BluSunrize requested changes
LGTM except for minor changes

2022-06-06 16:38 UTC, BluSunrize commented on src/special_elements.js
> +        return <img className="item" alt={item.domain + ':' + item.name} src={URL.createObjectURL(blob)}/>;
Change this class name to something like `item-image` or `item-icon`.
I dislike using the same classes names for entirely different elements, and we already have a `div.item`

2022-06-06 16:38 UTC, BluSunrize commented on src/special_elements.js
> +        }
As above, should be replacable with a `data.inputs.map()` call.

2022-06-06 16:38 UTC, BluSunrize commented on src/styling/recipes.scss
> +
See above, change the class name please.

2022-06-06 16:38 UTC, BluSunrize commented on src/App.js
> +    }
Similar to Java's streams this should be achievable with
```javascript
supportedBranches = branchesJSON
    .map(b => b.name)
    .filter(name => name.startsWith('1.') && !EXCLUDED_VERSION_BRANCHES.has(name));
```

2022-06-06 16:38 UTC, BluSunrize commented on src/App.js
> +    }
Also, strings in Javascript with single quotes please, where possible.

2022-06-06 16:38 UTC, BluSunrize commented on src/resources.js
> +    "1.7.10", "1.8.9", "1.9.4", "1.10.2", "1.11.2", "1.13pre", "1.13"
Strings with single quotes, please.

2022-06-06 16:38 UTC, BluSunrize commented on src/special_elements.js
> +            }
Pretty sure this could be an Array.map call:

```javascript
let newIngredients= json.ingredients.map(ingr => await PreparedIngredient.of(ingr, branch));
```

At least I'm fairly sure `await` is valid in an arrow function

2022-06-06 20:33 UTC, BluSunrize approved these changes
LGTM

2022-06-07 04:34 UTC, malte0811 commented
You'll need to actually merge this PR if you think it's ready, I don't have push access to this repo.

2022-06-07 07:37 UTC, merged